server:
  port: 8020

spring:
  application:
    name: promotion-app  # consul注册中心相关配置
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery: # 是否注册（默认为true）
        register: true
        # 服务名称
        service-name: ${spring.application.name}
        # 展示实例的ip（默认是false）
        prefer-ip-address: true
        # 实例id名称（默认是${spring.application.name}:comma,separated,profiles:${server.port}）
        # instance-id: ${spring.application.name}

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/promotion-app?serverTimezone=GMT&useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: 123456
  flyway:
    baseline-on-migrate: true
    enabled: true

  # Redis数据库索引（默认为0）
  redis:
    database: 0
    host: localhost
    port: 6379
    # password
    #客户端超时时间
    timeout: 0
    pool:
      max-active: 200
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
  #spring-session 不使用, 所有状态都存在数据库里，不需要在redis里再用session存状态
  session.store-type: none


# rocketmq配置信息
rocketmq:
  # rocketmq服务接入地址
  name-server: localhost:9876
  # Consumer 配置项
  consumer:
    listeners: # 配置某个消费分组，是否监听指定 Topic 。结构为 Map<消费者分组, <Topic, Boolean>> 。默认情况下，不配置表示监听。
      test-consumer-group:
        topic1: false # 关闭 test-consumer-group 对 topic1 的监听消费


# costumer config
promotion:
  stock-strategy: optimistic # [oversell, sync, optimistic]
  topic:
    lock-stock: lock-stock
    lock-stock-group: LS-G
    revert-stock: revert-stock
    revert-stock-group: RS-G
    deduct-stock: deduct-stock
    deduct-stock-group: DS-G
