/*
 * This file is generated by jOOQ.
 */
package com.skillup.infrastructure.jooq;


import com.skillup.infrastructure.jooq.tables.Commodity;


/**
 * Convenience access to all tables in commodity-app.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>commodity-app.commodity</code>.
     */
    public static final Commodity COMMODITY = Commodity.COMMODITY;
}
