/*
 * This file is generated by jOOQ.
 */
package com.skillup.infrastructure.jooq;


import com.skillup.infrastructure.jooq.tables.Promotion;
import com.skillup.infrastructure.jooq.tables.PromotionLog;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PromotionApp extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>promotion-app</code>
     */
    public static final PromotionApp PROMOTION_APP = new PromotionApp();

    /**
     * The table <code>promotion-app.promotion</code>.
     */
    public final Promotion PROMOTION = Promotion.PROMOTION;

    /**
     * The table <code>promotion-app.promotion_log</code>.
     */
    public final PromotionLog PROMOTION_LOG = PromotionLog.PROMOTION_LOG;

    /**
     * No further instances allowed
     */
    private PromotionApp() {
        super("promotion-app", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Promotion.PROMOTION,
            PromotionLog.PROMOTION_LOG);
    }
}
