/*
 * This file is generated by jOOQ.
 */
package com.skillup.infrastructure.jooq;


import com.skillup.infrastructure.jooq.tables.Orders;


/**
 * Convenience access to all tables in order-app-1.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>order-app-1.orders</code>.
     */
    public static final Orders ORDERS = Orders.ORDERS;
}
